name: Build puppet/centos-7-x86_64

on:
  push:
    paths:
      - 'puppetlabs/centos-7-x86_64/*'
  # Manual trigger for testing.
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build puppetlabs/centos-7-x86_64 --tag centos-7-x86_64:$(date +'%Y%m%d%H%M%S')
